/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sudoku;

/**
 *
 * @author hackrush
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainFrame = new javax.swing.JPanel();
        Block1 = new javax.swing.JPanel();
        Box11 = new javax.swing.JLabel();
        Box12 = new javax.swing.JLabel();
        Box13 = new javax.swing.JLabel();
        Box14 = new javax.swing.JLabel();
        Box15 = new javax.swing.JLabel();
        Box16 = new javax.swing.JLabel();
        Box17 = new javax.swing.JLabel();
        Box18 = new javax.swing.JLabel();
        Box19 = new javax.swing.JLabel();
        Block2 = new javax.swing.JPanel();
        Box21 = new javax.swing.JLabel();
        Box22 = new javax.swing.JLabel();
        Box23 = new javax.swing.JLabel();
        Box24 = new javax.swing.JLabel();
        Box25 = new javax.swing.JLabel();
        Box26 = new javax.swing.JLabel();
        Box27 = new javax.swing.JLabel();
        Box28 = new javax.swing.JLabel();
        Box29 = new javax.swing.JLabel();
        Block3 = new javax.swing.JPanel();
        Box31 = new javax.swing.JLabel();
        Box32 = new javax.swing.JLabel();
        Box33 = new javax.swing.JLabel();
        Box34 = new javax.swing.JLabel();
        Box35 = new javax.swing.JLabel();
        Box36 = new javax.swing.JLabel();
        Box37 = new javax.swing.JLabel();
        Box38 = new javax.swing.JLabel();
        Box39 = new javax.swing.JLabel();
        Block4 = new javax.swing.JPanel();
        Box41 = new javax.swing.JLabel();
        Box42 = new javax.swing.JLabel();
        Box43 = new javax.swing.JLabel();
        Box44 = new javax.swing.JLabel();
        Box45 = new javax.swing.JLabel();
        Box46 = new javax.swing.JLabel();
        Box47 = new javax.swing.JLabel();
        Box48 = new javax.swing.JLabel();
        Box49 = new javax.swing.JLabel();
        Block5 = new javax.swing.JPanel();
        Box51 = new javax.swing.JLabel();
        Box52 = new javax.swing.JLabel();
        Box53 = new javax.swing.JLabel();
        Box54 = new javax.swing.JLabel();
        Box55 = new javax.swing.JLabel();
        Box56 = new javax.swing.JLabel();
        Box57 = new javax.swing.JLabel();
        Box58 = new javax.swing.JLabel();
        Box59 = new javax.swing.JLabel();
        Block6 = new javax.swing.JPanel();
        Box61 = new javax.swing.JLabel();
        Box62 = new javax.swing.JLabel();
        Box63 = new javax.swing.JLabel();
        Box64 = new javax.swing.JLabel();
        Box65 = new javax.swing.JLabel();
        Box66 = new javax.swing.JLabel();
        Box67 = new javax.swing.JLabel();
        Box68 = new javax.swing.JLabel();
        Box69 = new javax.swing.JLabel();
        Block7 = new javax.swing.JPanel();
        Box71 = new javax.swing.JLabel();
        Box72 = new javax.swing.JLabel();
        Box73 = new javax.swing.JLabel();
        Box74 = new javax.swing.JLabel();
        Box75 = new javax.swing.JLabel();
        Box76 = new javax.swing.JLabel();
        Box77 = new javax.swing.JLabel();
        Box78 = new javax.swing.JLabel();
        Box79 = new javax.swing.JLabel();
        Block8 = new javax.swing.JPanel();
        Box81 = new javax.swing.JLabel();
        Box82 = new javax.swing.JLabel();
        Box83 = new javax.swing.JLabel();
        Box84 = new javax.swing.JLabel();
        Box85 = new javax.swing.JLabel();
        Box86 = new javax.swing.JLabel();
        Box87 = new javax.swing.JLabel();
        Box88 = new javax.swing.JLabel();
        Box89 = new javax.swing.JLabel();
        Block9 = new javax.swing.JPanel();
        Box91 = new javax.swing.JLabel();
        Box92 = new javax.swing.JLabel();
        Box93 = new javax.swing.JLabel();
        Box94 = new javax.swing.JLabel();
        Box95 = new javax.swing.JLabel();
        Box96 = new javax.swing.JLabel();
        Box97 = new javax.swing.JLabel();
        Box98 = new javax.swing.JLabel();
        Box99 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);

        MainFrame.setLayout(new java.awt.GridLayout(3, 3));

        Block1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Block1.setLayout(new java.awt.GridLayout(3, 3));

        Box11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box11.setText("jLabel1");
        Box11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block1.add(Box11);

        Box12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box12.setText("jLabel1");
        Box12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block1.add(Box12);

        Box13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box13.setText("jLabel1");
        Box13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block1.add(Box13);

        Box14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box14.setText("jLabel1");
        Box14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block1.add(Box14);

        Box15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box15.setText("jLabel1");
        Box15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block1.add(Box15);

        Box16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box16.setText("jLabel1");
        Box16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block1.add(Box16);

        Box17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box17.setText("jLabel1");
        Box17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block1.add(Box17);

        Box18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box18.setText("jLabel1");
        Box18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block1.add(Box18);

        Box19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box19.setText("jLabel1");
        Box19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block1.add(Box19);

        MainFrame.add(Block1);

        Block2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Block2.setLayout(new java.awt.GridLayout(3, 3));

        Box21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box21.setText("jLabel1");
        Box21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block2.add(Box21);

        Box22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box22.setText("jLabel1");
        Box22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block2.add(Box22);

        Box23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box23.setText("jLabel1");
        Box23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block2.add(Box23);

        Box24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box24.setText("jLabel1");
        Box24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block2.add(Box24);

        Box25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box25.setText("jLabel1");
        Box25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block2.add(Box25);

        Box26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box26.setText("jLabel1");
        Box26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block2.add(Box26);

        Box27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box27.setText("jLabel1");
        Box27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block2.add(Box27);

        Box28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box28.setText("jLabel1");
        Box28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block2.add(Box28);

        Box29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box29.setText("jLabel1");
        Box29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block2.add(Box29);

        MainFrame.add(Block2);

        Block3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Block3.setLayout(new java.awt.GridLayout(3, 3));

        Box31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box31.setText("jLabel1");
        Box31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block3.add(Box31);

        Box32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box32.setText("jLabel1");
        Box32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block3.add(Box32);

        Box33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box33.setText("jLabel1");
        Box33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block3.add(Box33);

        Box34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box34.setText("jLabel1");
        Box34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block3.add(Box34);

        Box35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box35.setText("jLabel1");
        Box35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block3.add(Box35);

        Box36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box36.setText("jLabel1");
        Box36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block3.add(Box36);

        Box37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box37.setText("jLabel1");
        Box37.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block3.add(Box37);

        Box38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box38.setText("jLabel1");
        Box38.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block3.add(Box38);

        Box39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box39.setText("jLabel1");
        Box39.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block3.add(Box39);

        MainFrame.add(Block3);

        Block4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Block4.setLayout(new java.awt.GridLayout(3, 3));

        Box41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box41.setText("jLabel1");
        Box41.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block4.add(Box41);

        Box42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box42.setText("jLabel1");
        Box42.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block4.add(Box42);

        Box43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box43.setText("jLabel1");
        Box43.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block4.add(Box43);

        Box44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box44.setText("jLabel1");
        Box44.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block4.add(Box44);

        Box45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box45.setText("jLabel1");
        Box45.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block4.add(Box45);

        Box46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box46.setText("jLabel1");
        Box46.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block4.add(Box46);

        Box47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box47.setText("jLabel1");
        Box47.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block4.add(Box47);

        Box48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box48.setText("jLabel1");
        Box48.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block4.add(Box48);

        Box49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box49.setText("jLabel1");
        Box49.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block4.add(Box49);

        MainFrame.add(Block4);

        Block5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Block5.setLayout(new java.awt.GridLayout(3, 3));

        Box51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box51.setText("jLabel1");
        Box51.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block5.add(Box51);

        Box52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box52.setText("jLabel1");
        Box52.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block5.add(Box52);

        Box53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box53.setText("jLabel1");
        Box53.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block5.add(Box53);

        Box54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box54.setText("jLabel1");
        Box54.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block5.add(Box54);

        Box55.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box55.setText("jLabel1");
        Box55.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block5.add(Box55);

        Box56.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box56.setText("jLabel1");
        Box56.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block5.add(Box56);

        Box57.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box57.setText("jLabel1");
        Box57.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block5.add(Box57);

        Box58.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box58.setText("jLabel1");
        Box58.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block5.add(Box58);

        Box59.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box59.setText("jLabel1");
        Box59.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block5.add(Box59);

        MainFrame.add(Block5);

        Block6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Block6.setLayout(new java.awt.GridLayout(3, 3));

        Box61.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box61.setText("jLabel1");
        Box61.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block6.add(Box61);

        Box62.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box62.setText("jLabel1");
        Box62.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block6.add(Box62);

        Box63.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box63.setText("jLabel1");
        Box63.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block6.add(Box63);

        Box64.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box64.setText("jLabel1");
        Box64.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block6.add(Box64);

        Box65.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box65.setText("jLabel1");
        Box65.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block6.add(Box65);

        Box66.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box66.setText("jLabel1");
        Box66.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block6.add(Box66);

        Box67.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box67.setText("jLabel1");
        Box67.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block6.add(Box67);

        Box68.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box68.setText("jLabel1");
        Box68.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block6.add(Box68);

        Box69.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box69.setText("jLabel1");
        Box69.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block6.add(Box69);

        MainFrame.add(Block6);

        Block7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Block7.setLayout(new java.awt.GridLayout(3, 3));

        Box71.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box71.setText("jLabel1");
        Box71.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block7.add(Box71);

        Box72.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box72.setText("jLabel1");
        Box72.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block7.add(Box72);

        Box73.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box73.setText("jLabel1");
        Box73.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block7.add(Box73);

        Box74.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box74.setText("jLabel1");
        Box74.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block7.add(Box74);

        Box75.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box75.setText("jLabel1");
        Box75.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block7.add(Box75);

        Box76.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box76.setText("jLabel1");
        Box76.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block7.add(Box76);

        Box77.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box77.setText("jLabel1");
        Box77.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block7.add(Box77);

        Box78.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box78.setText("jLabel1");
        Box78.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block7.add(Box78);

        Box79.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box79.setText("jLabel1");
        Box79.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block7.add(Box79);

        MainFrame.add(Block7);

        Block8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Block8.setLayout(new java.awt.GridLayout(3, 3));

        Box81.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box81.setText("jLabel1");
        Box81.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block8.add(Box81);

        Box82.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box82.setText("jLabel1");
        Box82.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block8.add(Box82);

        Box83.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box83.setText("jLabel1");
        Box83.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block8.add(Box83);

        Box84.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box84.setText("jLabel1");
        Box84.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block8.add(Box84);

        Box85.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box85.setText("jLabel1");
        Box85.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block8.add(Box85);

        Box86.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box86.setText("jLabel1");
        Box86.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block8.add(Box86);

        Box87.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box87.setText("jLabel1");
        Box87.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block8.add(Box87);

        Box88.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box88.setText("jLabel1");
        Box88.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block8.add(Box88);

        Box89.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box89.setText("jLabel1");
        Box89.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block8.add(Box89);

        MainFrame.add(Block8);

        Block9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Block9.setLayout(new java.awt.GridLayout(3, 3));

        Box91.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box91.setText("jLabel1");
        Box91.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block9.add(Box91);

        Box92.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box92.setText("jLabel1");
        Box92.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block9.add(Box92);

        Box93.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box93.setText("jLabel1");
        Box93.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block9.add(Box93);

        Box94.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box94.setText("jLabel1");
        Box94.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block9.add(Box94);

        Box95.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box95.setText("jLabel1");
        Box95.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block9.add(Box95);

        Box96.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box96.setText("jLabel1");
        Box96.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block9.add(Box96);

        Box97.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box97.setText("jLabel1");
        Box97.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block9.add(Box97);

        Box98.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box98.setText("jLabel1");
        Box98.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block9.add(Box98);

        Box99.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Box99.setText("jLabel1");
        Box99.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Block9.add(Box99);

        MainFrame.add(Block9);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 756, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 756, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Block1;
    private javax.swing.JPanel Block2;
    private javax.swing.JPanel Block3;
    private javax.swing.JPanel Block4;
    private javax.swing.JPanel Block5;
    private javax.swing.JPanel Block6;
    private javax.swing.JPanel Block7;
    private javax.swing.JPanel Block8;
    private javax.swing.JPanel Block9;
    private javax.swing.JLabel Box11;
    private javax.swing.JLabel Box12;
    private javax.swing.JLabel Box13;
    private javax.swing.JLabel Box14;
    private javax.swing.JLabel Box15;
    private javax.swing.JLabel Box16;
    private javax.swing.JLabel Box17;
    private javax.swing.JLabel Box18;
    private javax.swing.JLabel Box19;
    private javax.swing.JLabel Box21;
    private javax.swing.JLabel Box22;
    private javax.swing.JLabel Box23;
    private javax.swing.JLabel Box24;
    private javax.swing.JLabel Box25;
    private javax.swing.JLabel Box26;
    private javax.swing.JLabel Box27;
    private javax.swing.JLabel Box28;
    private javax.swing.JLabel Box29;
    private javax.swing.JLabel Box31;
    private javax.swing.JLabel Box32;
    private javax.swing.JLabel Box33;
    private javax.swing.JLabel Box34;
    private javax.swing.JLabel Box35;
    private javax.swing.JLabel Box36;
    private javax.swing.JLabel Box37;
    private javax.swing.JLabel Box38;
    private javax.swing.JLabel Box39;
    private javax.swing.JLabel Box41;
    private javax.swing.JLabel Box42;
    private javax.swing.JLabel Box43;
    private javax.swing.JLabel Box44;
    private javax.swing.JLabel Box45;
    private javax.swing.JLabel Box46;
    private javax.swing.JLabel Box47;
    private javax.swing.JLabel Box48;
    private javax.swing.JLabel Box49;
    private javax.swing.JLabel Box51;
    private javax.swing.JLabel Box52;
    private javax.swing.JLabel Box53;
    private javax.swing.JLabel Box54;
    private javax.swing.JLabel Box55;
    private javax.swing.JLabel Box56;
    private javax.swing.JLabel Box57;
    private javax.swing.JLabel Box58;
    private javax.swing.JLabel Box59;
    private javax.swing.JLabel Box61;
    private javax.swing.JLabel Box62;
    private javax.swing.JLabel Box63;
    private javax.swing.JLabel Box64;
    private javax.swing.JLabel Box65;
    private javax.swing.JLabel Box66;
    private javax.swing.JLabel Box67;
    private javax.swing.JLabel Box68;
    private javax.swing.JLabel Box69;
    private javax.swing.JLabel Box71;
    private javax.swing.JLabel Box72;
    private javax.swing.JLabel Box73;
    private javax.swing.JLabel Box74;
    private javax.swing.JLabel Box75;
    private javax.swing.JLabel Box76;
    private javax.swing.JLabel Box77;
    private javax.swing.JLabel Box78;
    private javax.swing.JLabel Box79;
    private javax.swing.JLabel Box81;
    private javax.swing.JLabel Box82;
    private javax.swing.JLabel Box83;
    private javax.swing.JLabel Box84;
    private javax.swing.JLabel Box85;
    private javax.swing.JLabel Box86;
    private javax.swing.JLabel Box87;
    private javax.swing.JLabel Box88;
    private javax.swing.JLabel Box89;
    private javax.swing.JLabel Box91;
    private javax.swing.JLabel Box92;
    private javax.swing.JLabel Box93;
    private javax.swing.JLabel Box94;
    private javax.swing.JLabel Box95;
    private javax.swing.JLabel Box96;
    private javax.swing.JLabel Box97;
    private javax.swing.JLabel Box98;
    private javax.swing.JLabel Box99;
    private javax.swing.JPanel MainFrame;
    // End of variables declaration//GEN-END:variables
}
